env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    bot_api: "ENCRYPTED[d5f8289d835b201789b2b31e728d0cd82a100f1b47ddec69dd6ba49a3712fcfa2719b220fc6a8894865df517a78332ca]"

task:
  name: Test
  timeout_in: 5m
  container:
      image: apon77/aosp:cirrus
      cpu: 2
      memory: 4G
  env_script: env
  show_script: cat $CIRRUS_WORKING_DIR/build_rom.sh
  #notify_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/notify.sh | bash
  test_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/test.sh | bash

task:
  name: Build
  depends_on: Test
  timeout_in: 4h
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
      volumes:
        - /home/cirrus/roms:/home/cirrus/roms
        - /home/cirrus/ccache:/home/cirrus/ccache
        - /home/cirrus/.config:/home/cirrus/.config
  show_script: cat $CIRRUS_WORKING_DIR/build_rom.sh
  test_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/test.sh | bash
  sync_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/sync.sh | bash
  tsync_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/tsync.sh | bash
  build_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/build.sh | bash
  ccache_stats_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/ccache_stats.sh | bash
  upload_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/upload.sh | bash
  remove_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/remove.sh | bash

task:
  name: Post Build
  skip_notifications: true
  depends_on: Build
  timeout_in: 5m
  container:
      image: apon77/aosp:cirrus
      cpu: 2
      memory: 4G
  test_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/test.sh | bash
  post_build_script: curl -s https://raw.githubusercontent.com/ndrancs/ktx2/master/ci/post_build.sh | bash
